services:
  rds_postgres:
    image: postgres:14
    container_name: "rds_postgres"
    restart: always
    healthcheck:
      test: [ "CMD", "sh", "-c", "pg_isready -d ${RDS_POSTGRES_DB} -U ${RDS_POSTGRES_USER}" ]
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      - POSTGRES_DB=${RDS_POSTGRES_DB}
      - POSTGRES_USER=${RDS_POSTGRES_USER}
      - POSTGRES_PASSWORD=${RDS_POSTGRES_PASSWORD}
    volumes:
      - rds_postgres_data:/var/lib/postgresql/data
      - ./data:/opt/sql-data
      - ./scripts/sql:/docker-entrypoint-initdb.d
    ports:
    - 5436:5432
    networks:
      - etl-network



volumes:
  rds_postgres_data:

networks:
  etl-network:
    driver: bridge